spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/outbox_demo
      # Important: Replica Set is required for Transactions
      auto-index-creation: true

# Custom Outbox Scheduler Configuration
outbox:
  scheduler:
    enabled: true
    poll-interval-ms: 2000
    batch-size: 10
    max-retries: 10
    delete-after-processing: false

logging:
  level:
    io.namastack.sample: DEBUG
    org.springframework.data.mongodb: DEBUG
